services:
  web:
    image: fholzer/nginx-brotli:latest
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./cert.key:/etc/nginx/cert.key
    links:
      - api
    networks:
      - bacos

  api:
    restart: unless-stopped
    build:
      context: ./docker/node
    volumes:
      - .:/var/www:delegated
    networks:
      - bacos

  redis:
    restart: unless-stopped
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - bacos

  vite:
    restart: unless-stopped
    build:
      context: ./docker/vite
    volumes:
      - .:/var/www:delegated
    ports:
      - 5173:5173

networks:
  bacos:
    driver: bridge